server:
  port: 8081
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/apollov2
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop